version: '3.8'
services:
  pg:
    image: postgres:15
    restart: always
    ports:
      - '5432:5432'
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=root
      - POSTGRES_DB=ecommerce
      - POSTGRES_PASSWORD=post1221
    volumes:
      - pg-data:/var/lib/postgresql/data
  ecommerce:
    build: .
    ports:
      - '3520:3520'
    links:
      - pg
    depends_on:
      - pg
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: 'admin@admin.com'
      PGADMIN_DEFAULT_PASSWORD: 'admin'
    ports:
      - '81:80'
    depends_on:
      - pg

volumes:
  pg-data:
